"""Per-agent profile targets.

A Target turns one profile into that agent's native form and takes profile-owned
servers out of the agent's everyday config. Claude Code gets a subagent file whose
inline `mcpServers` connect only while the subagent runs; the main session never
loads them.
"""
import json
import os
import tempfile

GENERATED = "<!-- generated by governor profilesync from {src}; edit that file and run `govctl profiles-sync` -->"


def _atomic_write(path, text, mode=0o600):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path))
    os.fchmod(fd, mode)
    with os.fdopen(fd, "w") as fh:
        fh.write(text)
    os.replace(tmp, path)


def _yaml_list(items):
    return "[" + ", ".join(json.dumps(i) for i in items) + "]"


class ClaudeCode:
    name = "claude_code"
    label = "Claude Code"
    agents_dir = os.path.expanduser("~/.claude/agents")
    config_file = os.path.expanduser("~/.claude.json")

    def agent_path(self, profile):
        return os.path.join(self.agents_dir, profile["name"] + ".md")

    def render(self, profile, servers, src):
        # Frontmatter values are emitted as JSON, which is valid YAML flow syntax,
        # so server definitions round-trip without a YAML library.
        fm = [
            f"name: {profile['name']}",
            f"description: {json.dumps(profile['description'])}",
        ]
        if profile.get("model"):
            fm.append(f"model: {profile['model']}")
        if profile.get("tools"):
            fm.append(f"tools: {_yaml_list(profile['tools'])}")
        if profile.get("disallowed"):
            fm.append(f"disallowedTools: {_yaml_list(profile['disallowed'])}")
        fm.append("mcpServers:")
        for name, definition in servers.items():
            fm.append(f"  - {name}: {json.dumps(definition)}")
        return "---\n" + "\n".join(fm) + "\n---\n\n" + GENERATED.format(src=src) + "\n\n" + profile["body"].strip() + "\n"

    def write(self, profile, servers, src, dry_run):
        path = self.agent_path(profile)
        if os.path.isfile(path):
            with open(path) as fh:
                if "generated by governor profilesync" not in fh.read():
                    raise ValueError(f"{path} exists and was not generated by profilesync; rename the profile or move that file")
        text = self.render(profile, servers, src)
        if not dry_run:
            _atomic_write(path, text)
        return path

    def remove_stale(self, previous, current, dry_run):
        stale = sorted(set(previous) - set(current))
        for path in stale:
            if dry_run or not os.path.isfile(path):
                continue
            with open(path) as fh:
                if "generated by governor profilesync" not in fh.read():
                    continue
            os.remove(path)
        return stale

    def retire_everyday(self, names, dry_run):
        """Drop these servers from the user-scope config. Returns the names removed."""
        try:
            with open(self.config_file) as fh:
                data = json.load(fh)
        except FileNotFoundError:
            return []
        everyday = data.get("mcpServers") or {}
        removed = sorted(n for n in names if n in everyday)
        if removed and not dry_run:
            for n in removed:
                del everyday[n]
            _atomic_write(self.config_file, json.dumps(data, indent=2), os.stat(self.config_file).st_mode & 0o777)
        return removed


TARGETS = {"claude_code": ClaudeCode()}
ALL_TARGETS = list(TARGETS)
