"""Per-agent profile targets.

A Target turns one profile into that agent's native form and takes profile-owned
servers out of the agent's everyday config. Claude Code gets a subagent file whose
inline `mcpServers` connect only while the subagent runs; the main session never
loads them. Codex gets a config profile (`~/.codex/<name>.config.toml`) that
`codex -p <name>` layers on top of the base config, for a session of its own.
"""
import json
import os
import re
import tempfile

MARK = "generated by governor profilesync"
GENERATED = "<!-- " + MARK + " from {src}; edit that file and run `govctl profiles-sync` -->"


def _atomic_write(path, text, mode=0o600):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path))
    os.fchmod(fd, mode)
    with os.fdopen(fd, "w") as fh:
        fh.write(text)
    os.replace(tmp, path)


def _yaml_list(items):
    return "[" + ", ".join(json.dumps(i) for i in items) + "]"


class Target:
    def _guarded_write(self, path, text, dry_run):
        if os.path.isfile(path):
            with open(path) as fh:
                if MARK not in fh.read():
                    raise ValueError(f"{path} exists and was not generated by profilesync; rename the profile or move that file")
        if not dry_run:
            _atomic_write(path, text)
        return path

    def remove_stale(self, previous, current, dry_run):
        stale = sorted(set(previous) - set(current))
        for path in stale:
            if dry_run or not os.path.isfile(path):
                continue
            with open(path) as fh:
                if MARK not in fh.read():
                    continue
            os.remove(path)
        return stale


class ClaudeCode(Target):
    name = "claude_code"
    label = "Claude Code"
    agents_dir = os.path.expanduser("~/.claude/agents")
    config_file = os.path.expanduser("~/.claude.json")

    def agent_path(self, profile):
        return os.path.join(self.agents_dir, profile["name"] + ".md")

    def render(self, profile, servers, src):
        # Frontmatter values are emitted as JSON, which is valid YAML flow syntax,
        # so server definitions round-trip without a YAML library.
        fm = [
            f"name: {profile['name']}",
            f"description: {json.dumps(profile['description'])}",
        ]
        if profile.get("model"):
            fm.append(f"model: {profile['model']}")
        if profile.get("tools"):
            fm.append(f"tools: {_yaml_list(profile['tools'])}")
        if profile.get("disallowed"):
            fm.append(f"disallowedTools: {_yaml_list(profile['disallowed'])}")
        fm.append("mcpServers:")
        for name, definition in servers.items():
            fm.append(f"  - {name}: {json.dumps(definition)}")
        return "---\n" + "\n".join(fm) + "\n---\n\n" + GENERATED.format(src=src) + "\n\n" + profile["body"].strip() + "\n"

    def write(self, profile, servers, src, dry_run):
        return [self._guarded_write(self.agent_path(profile), self.render(profile, servers, src), dry_run)]

    def retire_everyday(self, names, dry_run):
        """Drop these servers from the user-scope config. Returns the names removed."""
        try:
            with open(self.config_file) as fh:
                data = json.load(fh)
        except FileNotFoundError:
            return []
        everyday = data.get("mcpServers") or {}
        removed = sorted(n for n in names if n in everyday)
        if removed and not dry_run:
            for n in removed:
                del everyday[n]
            _atomic_write(self.config_file, json.dumps(data, indent=2), os.stat(self.config_file).st_mode & 0o777)
        return removed


def _toml(value):
    """A TOML value from JSON-shaped data: JSON strings and arrays are valid TOML."""
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{json.dumps(k)} = {_toml(v)}" for k, v in value.items()) + " }"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value)


class Codex(Target):
    name = "codex"
    label = "Codex"
    home = os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex"))

    @property
    def config_file(self):
        return os.path.join(self.home, "config.toml")

    def _servers(self, profile, servers):
        """[mcp_servers.*] tables in Codex's schema, from registry (.mcp.json-shaped) definitions."""
        blocked = {}
        for tool in profile.get("disallowed") or []:
            _, server, name = tool.split("__", 2)
            blocked.setdefault(server, []).append(name)
        out = []
        for name, d in servers.items():
            lines = [f"[mcp_servers.{name}]"]
            if d.get("url"):
                lines.append(f"url = {_toml(d['url'])}")
                if d.get("headers"):
                    lines.append(f"http_headers = {_toml(d['headers'])}")
            else:
                lines.append(f"command = {_toml(d['command'])}")
                lines.append(f"args = {_toml(d.get('args') or [])}")
                if d.get("env"):
                    lines.append(f"env = {_toml(d['env'])}")
            if blocked.get(name):
                lines.append(f"disabled_tools = {_toml(blocked[name])}")
            out.append("\n".join(lines))
        return "\n\n".join(out)

    def render(self, profile, servers, src, session):
        head = [f"# {MARK} from {src}; edit that file and run `govctl profiles-sync`"]
        if not session:
            head += [f"name = {_toml(profile['name'])}", f"description = {_toml(profile['description'])}"]
        if profile.get("model"):
            head.append(f"model = {_toml(profile['model'])}")
        # Codex defers MCP tools behind a tool search; without this a worker can report them missing.
        brief = ("Your MCP tools may be deferred: search your tools for them before concluding one is unavailable.\n\n"
                 + profile["body"].strip())
        head.append(f"developer_instructions = {_toml(brief)}")
        return "\n".join(head) + "\n\n" + self._servers(profile, servers) + "\n"

    def write(self, profile, servers, src, dry_run):
        # Session profile only. Codex 0.155 starts a custom agent (`agents/<name>.toml`)
        # without its `mcp_servers`, so a worker there would have none of its tools;
        # emit that file again via render(session=False) once Codex honors them.
        session = os.path.join(self.home, profile["name"] + ".config.toml")
        return [self._guarded_write(session, self.render(profile, servers, src, session=True), dry_run)]

    def retire_everyday(self, names, dry_run):
        """Drop these servers' tables (and their sub-tables) from config.toml."""
        try:
            with open(self.config_file) as fh:
                text = fh.read()
        except FileNotFoundError:
            return []
        removed, kept, skipping = set(), [], False
        header = re.compile(r"^\[mcp_servers\.([A-Za-z0-9_-]+)(?:\.[^\]]*)?\]\s*$")
        for line in text.splitlines(keepends=True):
            if line.startswith("["):
                m = header.match(line)
                skipping = bool(m and m.group(1) in names)
                if skipping:
                    removed.add(m.group(1))
            if not skipping:
                kept.append(line)
        if removed and not dry_run:
            _atomic_write(self.config_file, "".join(kept), os.stat(self.config_file).st_mode & 0o777)
        return sorted(removed)


TARGETS = {"claude_code": ClaudeCode(), "codex": Codex()}
ALL_TARGETS = list(TARGETS)
